print('Bee Movie Script According to all known laws of aviation, there is no way a bee should')
print('be able to fly. Its wings are too small to get its fat little body off the ground. The bee, of')
print('course, flies anyway because bees dont care what humans think is impossible. Yellow,')
print('black. Yellow, black. Yellow, black. Yellow, black. Ooh, black and yellow! Lets shake it')
print('up a little. Barry! Breakfast is ready! Ooming! Hang on a second. Hello? - Barry? -')
print('Adam? - Oan you believe this is happening? - I cant. Ill pick you up. Looking sharp. Use')
print('the stairs. Your father paid good money for those. Sorry. Im excited. Heres the')
print('graduate. Were very proud of you, son. A perfect report card, all Bs. Very proud. Ma! I')
print('got a thing going here. - You got lint on your fuzz. - Ow! Thats me! - Wave to us! Well')
print('be in row 118,000. - Bye! Barry, I told you, stop flying in the house! - Hey, Adam. - Hey,')
print('Barry. - Is that fuzz gel? - A little. Special day, graduation. Never thought Id make it.')
print('Three days grade school, three days high school. Those were awkward. Three days')
print('college. Im glad I took a day and hitchhiked around the hive. You did come back')
print('different. - Hi, Barry. - Artie, growing a mustache? Looks good. - Hear about Frankie?')
print('Yeah. - You going to the funeral? - No, Im not going. Everybody knows, sting someone,')
print('you die. Dont waste it on a squirrel. Such a hothead. I guess he could have just gotten')
print('out of the way. I love this incorporating an amusement park into our day. Thats why')
print('we dont need vacations. Boy, quite a bit of pomp... under the circumstances. - Well,')
print('Adam, today we are men. - We are! - Bee-men. - Amen! Hallelujah! Students, faculty,')
print('distinguished bees, please welcome Dean Buzzwell. Welcome, New Hive Oity')
print('graduating class of... ...9:15. That concludes our ceremonies. And begins your career at')
print('Honex Industries! Will we pick ourjob today? I heard its just orientation. Heads up!')
print('Here we go. Keep your hands and antennas inside the tram at all times. - Wonder what')
print('itll be like? - A little scary. Welcome to Honex, a division of Honesco and a part of the')
print('Hexagon Group. This is it! Wow. Wow. We know that you, as a bee, have worked your')